name: Tests

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - ".gitignore"
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_THRESHOLD: 93

    steps:
      - name: set up python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: list_dir
        run: |
          pwd && ls -al

      - name: install requirements
        run: |
          pip install -r requirements.txt
          # make install_requirements

      # an automated security check
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
        with:
          fail_on_warnings: no

      - name: tests with pytest
        run: |
          pip install --no-cache pytest mock pytest-mock coverage && \
          coverage run -m pytest && \
          coverage report --fail-under=${COVERAGE_THRESHOLD}
          # make lint

      - name: run pylint
        run: |
          # make lint
          pip install pylint && \
          find . -type f -name "*.py" | xargs pylint
